### ISSUE TITLE
(Fabric) 1.21.1 crash when you search in the creative inventory. 

### ISSUE THREAD

**Issue by MaxBelleville** [ZsoltMolnarrr/CombatSpells#73]
I am running spell engine 1.0.5+1.21.1. 

```Reported exception thrown!
net.minecraft.class_148: charTyped event handler
	at net.minecraft.class_437.method_25412(class_437.java:436)
	at net.minecraft.class_309.method_1457(class_309.java:489)
	at net.minecraft.class_309.method_22677(class_309.java:500)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22675(class_309.java:500)
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:140)
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:135)
	at net.minecraft.class_1041.method_4482(class_1041.java:216)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43)
	at org.lwjgl.system.JNI.invokePI(Native Method)
	at org.lwjgl.glfw.GLFW.glfwGetKey(GLFW.java:3746)
	at net.minecraft.class_3675.method_15987(class_3675.java:473)
	at net.spell_engine.client.gui.SpellTooltip.addSpellInfo(SpellTooltip.java:91)
	at net.spell_engine.fabric.client.FabricClientMod.lambda$onInitializeClient$1(FabricClientMod.java:32)
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:35)
	at net.minecraft.class_1799.handler$zeg000$fabric-item-api-v1$getTooltip(class_1799.java:1636)
	at net.minecraft.class_1799.method_7950(class_1799.java:807)
	at net.minecraft.class_1124.method_60365(class_1124.java:52)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.class_1129.plainText(class_1129.java:21)
	at net.minecraft.class_1126.<init>(class_1126.java:16)
	at net.minecraft.class_1124.method_60350(class_1124.java:100)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)```

**Comment by ZsoltMolnarrr** [comment]
`Rendersystem called from wrong thread`

This doesn't happen normally.

Please provide full crashlog, and details on how exactly to reproduce this.

**Comment by MaxBelleville** [comment]
Thanks but I recently resolve this on my end by removing and reinstalling the mods I had. My guess some old mod I had was messing with it.
