### ISSUE TITLE
Crash with some armour (1.20.1) from a mixin

### ISSUE THREAD

**Issue by iacuobos** [ZsoltMolnarrr/CombatSpells#79]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_37908()" because "entity" is null
	at net.spell_engine.utils.TargetHelper.isTargetedByPlayer(TargetHelper.java:282)
	at net.minecraft.class_310.handler$loo000$spell_engine$hasOutline_HEAD_SpellEngine(class_310.java:46588)
	at net.minecraft.class_310.method_27022(class_310.java)
	at software.bernie.geckolib.renderer.GeoArmorRenderer.method_2828(GeoArmorRenderer.java:269)
	at santy.shadow_wizards.client.renderer.armour.LiannarArmourRender.method_2828(LiannarArmourRender.java:115)
	at net.minecraft.class_970.method_23192(class_970.java:119)
	at net.minecraft.class_970.method_4169(class_970.java:75)
	at net.minecraft.class_970.method_17157(class_970.java:44)
	at net.minecraft.class_970.method_4199(class_970.java:27)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:66)
	at net.minecraft.class_1007.method_3936(class_1007.java:43)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_490.method_29977(class_490.java:151)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1191)
	at net.minecraft.class_490.method_48472(class_490.java:151)
	at net.minecraft.class_490.method_2486(class_490.java:128)
	at net.minecraft.class_481.method_2389(class_481.java:794)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_481.method_25394(class_481.java:722)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$307(class_757.java)
	at net.minecraft.class_757.wrapOperation$mbm000$konkrete$wrapRenderScreenKonkrete(class_757.java:21628)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

**Comment by iacuobos** [comment]
Managed to fix it was a sodium thing
